openapi: 3.0.3
info:
  title: Restful UI Server Setting
  version: 0.9.0
externalDocs:
  description: Find out Restful UI
  url: https://github.com/funkjk/restful-ui
servers:
  - url: https://restful-ui.vercel.app/api
paths:
  /mcp/init:
    get:
      summary: Get MCP Server Information.
      description: Get MCP Server Informatin running (or not running) on Restful UI Server.
      responses:
        '200':
          description: Inforamtion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerState'
    post:
      summary: Initialize and start MCP Server.
      requestBody:
        description: Start MCP server with requested config
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/ServerConfig'
                - type: object
                  properties:
                    configurationId:
                      type: string
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                configurationId:
                  type: string
              required:
                - configurationId
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
    delete:
      summary: Stop MCP Server.
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
  /configs:
    get:
      summary: List MCP Server Configurations.
      parameters:
        - in: query
          name: filter
          schema:
            type: string
          required: false
          description: MCP Server Name filter
      responses:
        '200':
          description: Inforamtion
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServerConfigResponse'
    post:
      summary: Create MCP Server Configurations.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerConfig'
      responses:
        '201':
          description: Create MCP Server Configurations
          content:
            application/json:
              schema:
                type: object
                properties:
                  configurationId:
                    description: Configuration id
                    type: string
  /copy:
    post:
      summary: Copy MCP Server Configuration.
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                configurationId:
                  type: string
                  description: Configuration id
                newName:
                  type: string
                  description: New name
              required:
                - configurationId
      responses:
        '201':
          description: Create MCP Server Configurations
          content:
            application/json:
              schema:
                type: object
                properties:
                  configurationId:
                    description: Configuration id
                    type: string
  /configs/{configurationId}:
    get:
      summary: Get MCP Server Configuration.
      parameters:
        - in: path
          name: configurationId
          schema:
            type: string
          required: true
          description: MCP Server Configuration id
        - in: query
          name: filter
          schema:
            type: string
          required: false
          description: MCP Server Name filter
      responses:
        '200':
          description: Inforamtion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerConfigResponse'
    put:
      summary: Update MCP Server Configuration.
      parameters:
        - in: path
          name: configurationId
          schema:
            type: string
          required: true
          description: MCP Server Configuration id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerConfig'
      responses:
        '200':
          description: Inforamtion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
    delete:
      summary: Delete MCP Server Configuration.
      parameters:
        - in: path
          name: configurationId
          schema:
            type: string
          required: true
          description: MCP Server Configuration id
      responses:
        '200':
          description: Inforamtion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationResponse'
  /custom/configs/:
    get:
      responses:
        '200':
          description: Inforamtion
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
  /custom/configs/{configurationId}:
    get:
      responses:
        '200':
          description: Inforamtion
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    x-restfului-link: /custom/configs/{id}
                  name:
                    type: string

components:
  schemas:
    ServerConfigResponse:
      type: object
      properties:
        configurationId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        config:
          $ref: '#/components/schemas/ServerConfig'
    ServerConfig:
      type: object
      properties:
        openApiUrl:
          type: string
        serverName:
          type: string
        serverVersion:
          type: string
        timeout:
          type: number
        maxRetries:
          type: number
        requestSettings:
          $ref: '#/components/schemas/RequestSetting'
    ToolInfo:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        method:
          type: string
        path:
          type: string
        parameters:
          type: object
    ResourceInfo:
      type: object
      properties:
        uri:
          type: string
        name:
          type: string
        description:
          type: string
        method:
          type: string
        path:
          type: string
        parameters:
          type: object
        mimeType:
          type: string
    RequestSetting:
      type: object
      properties:
        headers:
          type: array
          items:
            type: object
        additionalQueryParameter:
          type: string
        basePath:
          type: string
        useProxy:
          type: boolean
    ServerState:
      type: object
      properties:
        isRunning:
          type: boolean
          example: true
        openApiUrl:
          type: string
          example: "https://restful-ui.vercel.app/oas/restful-api-sample-config.yaml"
        serverName:
          type: string
          example: "openapi-server"
        serverVersion:
          type: string
          example: "1.0.0"
        availableTools:
          type: array
          items:
            $ref: "#/components/schemas/ToolInfo"
        availableResources:
          type: array
          items:
            $ref: "#/components/schemas/ResourceInfo"
    OperationResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
      
            





