name: deploy-to-github-pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3.6.0
      
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      
      - name: build static resources
        run: npx cross-env BUILD_BASE_PATH=/restful-ui pnpm run build 
          
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build